
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				skeleton = true
				illusioner = true
				fox = true
				item_frame = true
				turtle = true
				bat = true
				creeper = true
				spider = true
				squid = true
				zombie = true
				glow_squid = true
				enderman = true
				item = true
				witch = true
				slime = true
				drowned = true
				horse = true
				armor_stand = true
				salmon = true
				cod = true
				painting = true
				pillager = true
				vindicator = true
				zombie_villager = true
				cave_spider = true
				sheep = true
				rabbit = true
				chest_minecart = true
				polar_bear = true
				villager = true
				cat = true
				iron_golem = true
				tropical_fish = true
				stray = true
				chicken = true
				wolf = true
				axolotl = true
				tnt_minecart = true
				pig = true
				bee = true
				goat = true
				guardian = true
				elder_guardian = true
				trident = true
				pufferfish = true
				minecart = true
				dolphin = true
				allay = true
				parrot = true
				cow = true
				piglin_brute = true
				arrow = true
				wither_skeleton = true
				husk = true
				ravager = true
				lightning_bolt = true
				llama = true
				donkey = true
				panda = true

			[light_sources.settings.entities.alexsmobs]
				crow = true
				blue_jay = true
				seagull = true
				lobster = true
				fly = true
				grizzly_bear = true
				raccoon = true
				cockroach = true
				orca = true
				banana_slug = true
				centipede_head = true
				centipede_body = true
				centipede_tail = true
				seal = true
				terrapin = true
				snow_leopard = true
				cachalot_whale = true
				cachalot_echo = true
				underminer = true
				flutter = true
				rocky_roller = true
				froststalker = true
				frilled_shark = true
				giant_squid = true
				blobfish = true
				skelewag = true
				comb_jelly = true
				gazelle = true
				bison = true
				flying_fish = true
				crocodile = true
				capuchin_monkey = true
				anteater = true
				leafcutter_ant = true
				rhinoceros = true
				maned_wolf = true
				kangaroo = true
				emu = true
				hummingbird = true
				gelada_monkey = true
				catfish = true
				murmur = true
				murmur_head = true
				tasmanian_devil = true
				skunk = true
				toucan = true
				gorilla = true
				elephant = true
				komodo_dragon = true
				moose = true
				tusklin = true
				bald_eagle = true
				ice_shard = true

			[light_sources.settings.entities.whisperwoods]
				zotzpyre = true
				moth = true
				wisp = true

			[light_sources.settings.entities.mekanismadditions]
				baby_creeper = true
				baby_skeleton = true
				baby_enderman = true
				baby_stray = true
				baby_wither_skeleton = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true
				frostbitten = true
				glacial_hunter = true
				hunter_wolf = true

			[light_sources.settings.entities.quark]
				stoneling = true
				toretoise = true
				forgotten = true
				crab = true
				shiba = true

			[light_sources.settings.entities.thermal]
				blitz = true
				blizz = true
				basalz = true

			[light_sources.settings.entities.savage_and_ravage]
				creepie = true
				griefer = true
				skeleton_villager = true
				iceologer = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				penguin = true

			[light_sources.settings.entities.upgrade_aquatic]
				pike = true
				thrasher = true
				great_thrasher = true
				nautilus = true

			[light_sources.settings.entities.cataclysm]
				the_harbinger = true
				deepling_brute = true
				deepling = true
				lionfish = true
				deepling_angler = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.windswept]
				chilled = true

			[light_sources.settings.entities.friendsandfoes]
				rascal = true
				glare = true
				copper_golem = true
				iceologer = true
				mauler = true
				moobloom = true

			[light_sources.settings.entities.environmental]
				deer = true
				duck = true
				yak = true

			[light_sources.settings.entities.galosphere]
				spectre = true
				sparkle = true

			[light_sources.settings.entities.hunterillager]
				hunterillager = true

			[light_sources.settings.entities.buzzier_bees]
				moobloom = true

			[light_sources.settings.entities.neapolitan]
				chimpanzee = true
				plantain_spider = true
				banana_peel = true

			[light_sources.settings.entities.man]
				manfromthefog = true

			[light_sources.settings.entities.pyromancer]
				frostcopper_golem = true

